@echo off
chcp 936 >nul
setlocal enabledelayedexpansion
pushd "%~dp0"
title 本地多模态助手 · 一键部署

echo ============================================================
echo            本地多模态助手 · 一键部署
echo ============================================================
echo.

REM ============ 1. 环境检查 ============
docker version >nul 2>&1
if errorlevel 1 (
    echo [错误] 未检测到可用的 Docker 引擎。
    echo        请先安装并启动 Docker Desktop：https://www.docker.com/products/docker-desktop/
    echo.
    pause
    exit /b 1
)
set "DC=docker compose"
docker compose version >nul 2>&1
if errorlevel 1 (
    docker-compose version >nul 2>&1
    if errorlevel 1 ( echo [错误] 未找到 docker compose，请升级 Docker Desktop。 & pause & exit /b 1 )
    set "DC=docker-compose"
)
echo [1/6] Docker 引擎正常

REM ============ 2. 显卡自动适配 ============
set "FILES=-f compose.yml"
set "HASGPU="
where nvidia-smi >nul 2>&1 && nvidia-smi >nul 2>&1 && set "HASGPU=1"
if defined HASGPU (
    set "FILES=!FILES! -f compose.gpu.yml"
    echo [2/6] 检测到 NVIDIA 显卡，已启用 GPU 加速
) else (
    echo [2/6] 未检测到 NVIDIA 显卡，使用 CPU 模式（功能完整，速度稍慢）
)

REM ---- 应用镜像二选一 ----
REM 两者功能完全相同，区别只在 torch：CUDA 版体积大，但绘图（文生图）能用显卡。
REM 对话/看图走的是 Ollama，与这里选哪个镜像无关。
set "APP_IMG=local-multimodal-app:latest"
set "APP_TAR=images\local-multimodal-app.tar"
if defined HASGPU (
    if exist "images\local-multimodal-app-gpu.tar" (
        set "APP_IMG=local-multimodal-app:gpu"
        set "APP_TAR=images\local-multimodal-app-gpu.tar"
        echo        应用镜像：CUDA 版（绘图走显卡）
    ) else (
        echo        应用镜像：CPU 版（没找到 GPU 镜像，绘图较慢）
    )
) else (
    echo        应用镜像：CPU 版
)
set "APP_IMG_SET=!APP_IMG!"

REM ============ 3. 选择 Ollama 模式 ============
REM 可用参数强制指定： 一键部署.bat direct  /  一键部署.bat bundled
set "MODE=%~1"
if not defined MODE (
    REM 宿主机已有 Ollama 在跑 → 直接连它，零下载
    curl -fsS -m 3 http://127.0.0.1:11434/api/version >nul 2>&1
    if errorlevel 1 (set "MODE=bundled") else (set "MODE=direct")
)

set "PROFILE="
if /i "%MODE%"=="direct" (
    echo [3/6] Ollama 模式：直连宿主机（零下载，用本机已装的 Ollama）
    set "MM_URL_SET=http://host.docker.internal:11434"
    set "MM_IMG_SET="
) else (
    echo [3/6] Ollama 模式：容器自带
    set "PROFILE=--profile bundled"
    set "MM_URL_SET=http://ollama:11434"
    set "MM_IMG_SET=local-multimodal-ollama:latest"
)
call :write_env

REM ============ 4. 准备镜像 ============
set "NEED_BUILD="
docker image inspect !APP_IMG! >nul 2>&1
if errorlevel 1 (
    if exist "!APP_TAR!" (
        echo [4/6] 正在导入应用镜像（首次运行需等待，文件较大）...
        docker load -i "!APP_TAR!"
        if errorlevel 1 ( echo [错误] 镜像导入失败。 & pause & exit /b 1 )
    ) else (
        echo [4/6] 未找到离线镜像，改为从源码构建（需联网）...
        set "NEED_BUILD=1"
    )
) else (
    echo [4/6] 应用镜像已存在：!APP_IMG!
)

if /i "%MODE%"=="bundled" (
    docker image inspect local-multimodal-ollama:latest >nul 2>&1
    if errorlevel 1 (
        call :ensure_ollama
        if errorlevel 1 (
            echo.
            echo [错误] 无法获取 Ollama 镜像。
            echo        可改用直连模式（用本机已装的 Ollama）：一键部署.bat direct
            pause & exit /b 1
        )
    )
)

if defined NEED_BUILD (
    %DC% !FILES! !PROFILE! build
    if errorlevel 1 ( echo [错误] 构建失败。 & pause & exit /b 1 )
)

REM ============ 5. 启动服务 ============
echo [5/6] 启动服务...
%DC% !FILES! !PROFILE! up -d
if errorlevel 1 ( echo. & echo [错误] 启动失败，可运行「查看状态.bat」查看原因。 & pause & exit /b 1 )

REM 顺带拉起「打开文件夹」小助手：容器里调不起宿主机的资源管理器，由它代劳
call :start_folder_agent

REM ============ 6. 等待就绪并打开浏览器 ============
echo [6/6] 等待服务就绪...
set "READY="
for /l %%i in (1,1,60) do (
    if not defined READY (
        curl -fsS -m 3 http://127.0.0.1:8000/api/health >nul 2>&1 && set "READY=1"
        if not defined READY >nul ping -n 3 127.0.0.1
    )
)

echo.
if defined READY (
    echo ============================================================
    echo   部署完成！正在打开浏览器：http://127.0.0.1:8000
    echo ============================================================
    start "" http://127.0.0.1:8000
) else (
    echo [提示] 服务还在启动中，稍等片刻手动打开：http://127.0.0.1:8000
    echo        查看进度：运行「查看状态.bat」
)

echo.
echo 模式：%MODE%    镜像：!APP_IMG!    停止：双击「停止运行.bat」    数据目录：%~dp0data
echo.
pause
popd
endlocal
goto :eof

REM ============================================================
REM  子过程：写 .env
REM  必须用「UTF-8 + 无 BOM」：compose 按 UTF-8 读 .env，
REM  而 cmd 的 echo 只会按本地代码页(GBK)写，中文路径会变乱码。
REM  命令行里不出现任何中文，路径由它自己取当前目录得到。
REM ============================================================
:write_env
powershell -NoProfile -ExecutionPolicy Bypass -Command "$p=(Get-Location).Path.Replace('\','/')+'/data'; $c=@('# auto-generated by deploy script','APP_PORT=8000',('APP_IMAGE='+$env:APP_IMG_SET),('MM_OLLAMA_URL='+$env:MM_URL_SET),'MM_MODEL=qwen3-vl:8b',('MM_HOST_DATA_DIR='+$p)); if ($env:MM_IMG_SET) { $c += ('OLLAMA_IMAGE='+$env:MM_IMG_SET) }; [IO.File]::WriteAllLines('.env',$c,(New-Object Text.UTF8Encoding($false)))"
exit /b 0

REM ============================================================
REM  子过程：启动宿主机「打开文件夹」小助手（隐藏窗口，常驻）
REM ============================================================
:start_folder_agent
if not exist "open-folder-agent.ps1" exit /b 0
set "MM_ROOT=%~dp0"
powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process -FilePath 'powershell.exe' -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',(Join-Path $env:MM_ROOT 'open-folder-agent.ps1')) -WindowStyle Hidden" >nul 2>&1
exit /b 0

REM ============================================================
REM  子过程：确保 local-multimodal-ollama 镜像就绪
REM  顺序：离线包 tar → 国内镜像源 → 官方源
REM ============================================================
:ensure_ollama
if not exist "images\local-multimodal-ollama.tar" goto :eo_pull
echo       正在导入离线 Ollama 镜像...
docker load -i "images\local-multimodal-ollama.tar"
if errorlevel 1 goto :eo_pull
exit /b 0

:eo_pull
echo       未找到离线镜像，正在从镜像源拉取（约 9GB，请耐心等待）...
for %%M in (docker.1ms.run docker.1panel.live docker.xuanyuan.me) do call :try_mirror %%M
docker image inspect local-multimodal-ollama:latest >nul 2>&1
if not errorlevel 1 exit /b 0
echo       镜像源均未成功，尝试官方源（国内可能非常慢）...
docker pull ollama/ollama:latest
if errorlevel 1 exit /b 1
docker tag ollama/ollama:latest local-multimodal-ollama:latest
exit /b 0

:try_mirror
docker image inspect local-multimodal-ollama:latest >nul 2>&1
if not errorlevel 1 exit /b 0
echo       尝试镜像源 %1 ...
docker pull %1/ollama/ollama:latest
if errorlevel 1 exit /b 1
docker tag %1/ollama/ollama:latest local-multimodal-ollama:latest
exit /b 0
